# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1085, 983)
        MainWindow.setMinimumSize(QtCore.QSize(800, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.page = QtWidgets.QTabWidget(self.centralwidget)
        self.page.setEnabled(True)
        self.page.setObjectName("page")
        self.tab_filters = QtWidgets.QWidget()
        self.tab_filters.setObjectName("tab_filters")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_filters)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.filter_input_image = QtWidgets.QLabel(self.tab_filters)
        self.filter_input_image.setMinimumSize(QtCore.QSize(322, 322))
        self.filter_input_image.setMaximumSize(QtCore.QSize(322, 322))
        self.filter_input_image.setFrameShape(QtWidgets.QFrame.Box)
        self.filter_input_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.filter_input_image.setObjectName("filter_input_image")
        self.gridLayout_3.addWidget(self.filter_input_image, 0, 1, 3, 1)
        self.filter_image_name = QtWidgets.QLabel(self.tab_filters)
        self.filter_image_name.setObjectName("filter_image_name")
        self.gridLayout_3.addWidget(self.filter_image_name, 1, 0, 1, 1)
        self.filter_browse_button = QtWidgets.QPushButton(self.tab_filters)
        self.filter_browse_button.setObjectName("filter_browse_button")
        self.gridLayout_3.addWidget(self.filter_browse_button, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_filters)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 40, 311, 41))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.filter_combo_box = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.filter_combo_box.setObjectName("filter_combo_box")
        self.filter_combo_box.addItem("")
        self.filter_combo_box.setItemText(0, "")
        self.filter_combo_box.addItem("")
        self.filter_combo_box.addItem("")
        self.filter_combo_box.addItem("")
        self.filter_combo_box.addItem("")
        self.filter_combo_box.addItem("")
        self.filter_combo_box.addItem("")
        self.filter_combo_box.addItem("")
        self.horizontalLayout.addWidget(self.filter_combo_box)
        self.groupBox_2 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_2.setGeometry(QtCore.QRect(380, 30, 311, 71))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(22, 102, 151, 39))
        self.label_4.setObjectName("label_4")
        self.noise_combo_box = QtWidgets.QComboBox(self.groupBox)
        self.noise_combo_box.setGeometry(QtCore.QRect(180, 110, 151, 22))
        self.noise_combo_box.setObjectName("noise_combo_box")
        self.noise_combo_box.addItem("")
        self.noise_combo_box.setItemText(0, "")
        self.noise_combo_box.addItem("")
        self.noise_combo_box.addItem("")
        self.noise_combo_box.addItem("")
        self.gridLayout_3.addWidget(self.groupBox, 4, 0, 1, 3)
        self.filter_noise_image = QtWidgets.QLabel(self.tab_filters)
        self.filter_noise_image.setMinimumSize(QtCore.QSize(322, 322))
        self.filter_noise_image.setMaximumSize(QtCore.QSize(322, 322))
        self.filter_noise_image.setFrameShape(QtWidgets.QFrame.Box)
        self.filter_noise_image.setTextFormat(QtCore.Qt.PlainText)
        self.filter_noise_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.filter_noise_image.setObjectName("filter_noise_image")
        self.gridLayout_3.addWidget(self.filter_noise_image, 0, 2, 3, 1)
        self.filter_image_size = QtWidgets.QLabel(self.tab_filters)
        self.filter_image_size.setObjectName("filter_image_size")
        self.gridLayout_3.addWidget(self.filter_image_size, 2, 0, 1, 1)
        self.filter_filter_image = QtWidgets.QLabel(self.tab_filters)
        self.filter_filter_image.setMinimumSize(QtCore.QSize(322, 322))
        self.filter_filter_image.setFrameShape(QtWidgets.QFrame.Box)
        self.filter_filter_image.setText("")
        self.filter_filter_image.setObjectName("filter_filter_image")
        self.gridLayout_3.addWidget(self.filter_filter_image, 3, 2, 1, 1)
        self.page.addTab(self.tab_filters, "")
        self.tab_histograms = QtWidgets.QWidget()
        self.tab_histograms.setObjectName("tab_histograms")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_histograms)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.hist_output_image = QtWidgets.QLabel(self.tab_histograms)
        self.hist_output_image.setMinimumSize(QtCore.QSize(322, 322))
        self.hist_output_image.setMaximumSize(QtCore.QSize(322, 322))
        self.hist_output_image.setFrameShape(QtWidgets.QFrame.Box)
        self.hist_output_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.hist_output_image.setObjectName("hist_output_image")
        self.gridLayout_4.addWidget(self.hist_output_image, 1, 3, 1, 1)
        self.hist_browse_image = QtWidgets.QPushButton(self.tab_histograms)
        self.hist_browse_image.setObjectName("hist_browse_image")
        self.gridLayout_4.addWidget(self.hist_browse_image, 0, 1, 1, 1)
        self.hist_image_size = QtWidgets.QLabel(self.tab_histograms)
        self.hist_image_size.setObjectName("hist_image_size")
        self.gridLayout_4.addWidget(self.hist_image_size, 2, 1, 1, 1)
        self.hist_image_name = QtWidgets.QLabel(self.tab_histograms)
        self.hist_image_name.setObjectName("hist_image_name")
        self.gridLayout_4.addWidget(self.hist_image_name, 1, 1, 1, 1)
        self.selectrgb = QtWidgets.QComboBox(self.tab_histograms)
        self.selectrgb.setObjectName("selectrgb")
        self.selectrgb.addItem("")
        self.selectrgb.addItem("")
        self.selectrgb.addItem("")
        self.selectrgb.addItem("")
        self.gridLayout_4.addWidget(self.selectrgb, 4, 1, 1, 1)
        self.hist_output_hist = QtWidgets.QGraphicsView(self.tab_histograms)
        self.hist_output_hist.setMaximumSize(QtCore.QSize(322, 322))
        self.hist_output_hist.setObjectName("hist_output_hist")
        self.gridLayout_4.addWidget(self.hist_output_hist, 4, 3, 1, 1)
        self.hist_input_image = QtWidgets.QLabel(self.tab_histograms)
        self.hist_input_image.setMinimumSize(QtCore.QSize(322, 322))
        self.hist_input_image.setMaximumSize(QtCore.QSize(322, 322))
        self.hist_input_image.setFrameShape(QtWidgets.QFrame.Box)
        self.hist_input_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.hist_input_image.setObjectName("hist_input_image")
        self.gridLayout_4.addWidget(self.hist_input_image, 1, 2, 1, 1)
        self.hist_input_hist = QtWidgets.QGraphicsView(self.tab_histograms)
        self.hist_input_hist.setMaximumSize(QtCore.QSize(322, 322))
        self.hist_input_hist.setObjectName("hist_input_hist")
        self.gridLayout_4.addWidget(self.hist_input_hist, 4, 2, 1, 1)
        self.hist_combbox = QtWidgets.QComboBox(self.tab_histograms)
        self.hist_combbox.setObjectName("hist_combbox")
        self.hist_combbox.addItem("")
        self.hist_combbox.addItem("")
        self.hist_combbox.addItem("")
        self.gridLayout_4.addWidget(self.hist_combbox, 3, 1, 1, 1)
        self.page.addTab(self.tab_histograms, "")
        self.tab_hybrid = QtWidgets.QWidget()
        self.tab_hybrid.setObjectName("tab_hybrid")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab_hybrid)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.hybrid_browse_image_1 = QtWidgets.QPushButton(self.tab_hybrid)
        self.hybrid_browse_image_1.setObjectName("hybrid_browse_image_1")
        self.gridLayout_2.addWidget(self.hybrid_browse_image_1, 0, 0, 1, 1)
        self.hybrid_input_image_1 = QtWidgets.QLabel(self.tab_hybrid)
        self.hybrid_input_image_1.setMaximumSize(QtCore.QSize(322, 322))
        self.hybrid_input_image_1.setFrameShape(QtWidgets.QFrame.Box)
        self.hybrid_input_image_1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.hybrid_input_image_1.setObjectName("hybrid_input_image_1")
        self.gridLayout_2.addWidget(self.hybrid_input_image_1, 0, 1, 3, 1)
        self.hybrid_output_image = QtWidgets.QLabel(self.tab_hybrid)
        self.hybrid_output_image.setMaximumSize(QtCore.QSize(322, 322))
        self.hybrid_output_image.setFrameShape(QtWidgets.QFrame.Box)
        self.hybrid_output_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.hybrid_output_image.setObjectName("hybrid_output_image")
        self.gridLayout_2.addWidget(self.hybrid_output_image, 0, 2, 7, 1)
        self.hybrid_image_1_name = QtWidgets.QLabel(self.tab_hybrid)
        self.hybrid_image_1_name.setObjectName("hybrid_image_1_name")
        self.gridLayout_2.addWidget(self.hybrid_image_1_name, 1, 0, 1, 1)
        self.hybrid_image_1_size = QtWidgets.QLabel(self.tab_hybrid)
        self.hybrid_image_1_size.setObjectName("hybrid_image_1_size")
        self.gridLayout_2.addWidget(self.hybrid_image_1_size, 2, 0, 1, 1)
        self.hybrid_browse_image_2 = QtWidgets.QPushButton(self.tab_hybrid)
        self.hybrid_browse_image_2.setObjectName("hybrid_browse_image_2")
        self.gridLayout_2.addWidget(self.hybrid_browse_image_2, 3, 0, 1, 1)
        self.hybrid_input_image_2 = QtWidgets.QLabel(self.tab_hybrid)
        self.hybrid_input_image_2.setMaximumSize(QtCore.QSize(322, 322))
        self.hybrid_input_image_2.setFrameShape(QtWidgets.QFrame.Box)
        self.hybrid_input_image_2.setTextFormat(QtCore.Qt.PlainText)
        self.hybrid_input_image_2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.hybrid_input_image_2.setObjectName("hybrid_input_image_2")
        self.gridLayout_2.addWidget(self.hybrid_input_image_2, 3, 1, 4, 1)
        self.hybrid_image_2_name = QtWidgets.QLabel(self.tab_hybrid)
        self.hybrid_image_2_name.setObjectName("hybrid_image_2_name")
        self.gridLayout_2.addWidget(self.hybrid_image_2_name, 4, 0, 1, 1)
        self.hybrid_image_2_size = QtWidgets.QLabel(self.tab_hybrid)
        self.hybrid_image_2_size.setObjectName("hybrid_image_2_size")
        self.gridLayout_2.addWidget(self.hybrid_image_2_size, 5, 0, 1, 1)
        self.hybrid_make_hybrid = QtWidgets.QPushButton(self.tab_hybrid)
        self.hybrid_make_hybrid.setObjectName("hybrid_make_hybrid")
        self.gridLayout_2.addWidget(self.hybrid_make_hybrid, 6, 0, 1, 1)
        self.page.addTab(self.tab_hybrid, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.hough_load = QtWidgets.QPushButton(self.tab)
        self.hough_load.setObjectName("hough_load")
        self.gridLayout_11.addWidget(self.hough_load, 0, 0, 1, 1)
        self.hough_input_image = QtWidgets.QLabel(self.tab)
        self.hough_input_image.setMinimumSize(QtCore.QSize(322, 322))
        self.hough_input_image.setMaximumSize(QtCore.QSize(322, 322))
        self.hough_input_image.setFrameShape(QtWidgets.QFrame.Box)
        self.hough_input_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.hough_input_image.setObjectName("hough_input_image")
        self.gridLayout_11.addWidget(self.hough_input_image, 0, 1, 3, 1)
        self.hough_output_image = QtWidgets.QLabel(self.tab)
        self.hough_output_image.setMinimumSize(QtCore.QSize(322, 322))
        self.hough_output_image.setMaximumSize(QtCore.QSize(322, 322))
        self.hough_output_image.setFrameShape(QtWidgets.QFrame.Box)
        self.hough_output_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.hough_output_image.setObjectName("hough_output_image")
        self.gridLayout_11.addWidget(self.hough_output_image, 0, 2, 3, 1)
        self.hough_image_name = QtWidgets.QLabel(self.tab)
        self.hough_image_name.setObjectName("hough_image_name")
        self.gridLayout_11.addWidget(self.hough_image_name, 1, 0, 1, 1)
        self.hough_image_size = QtWidgets.QLabel(self.tab)
        self.hough_image_size.setObjectName("hough_image_size")
        self.gridLayout_11.addWidget(self.hough_image_size, 2, 0, 1, 1)
        self.hough_apply = QtWidgets.QPushButton(self.tab)
        self.hough_apply.setObjectName("hough_apply")
        self.gridLayout_11.addWidget(self.hough_apply, 3, 0, 1, 1)
        self.groupBox_7 = QtWidgets.QGroupBox(self.tab)
        self.groupBox_7.setObjectName("groupBox_7")
        self.groupBox_8 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_8.setGeometry(QtCore.QRect(330, 10, 311, 161))
        self.groupBox_8.setObjectName("groupBox_8")
        self.hough_theta = QtWidgets.QLineEdit(self.groupBox_8)
        self.hough_theta.setGeometry(QtCore.QRect(10, 30, 113, 22))
        self.hough_theta.setObjectName("hough_theta")
        self.hough_rho = QtWidgets.QLineEdit(self.groupBox_8)
        self.hough_rho.setGeometry(QtCore.QRect(180, 30, 113, 22))
        self.hough_rho.setObjectName("hough_rho")
        self.hough_numpeaks = QtWidgets.QLineEdit(self.groupBox_8)
        self.hough_numpeaks.setGeometry(QtCore.QRect(100, 100, 113, 22))
        self.hough_numpeaks.setObjectName("hough_numpeaks")
        self.label_9 = QtWidgets.QLabel(self.groupBox_8)
        self.label_9.setGeometry(QtCore.QRect(30, 60, 55, 16))
        self.label_9.setObjectName("label_9")
        self.label_11 = QtWidgets.QLabel(self.groupBox_8)
        self.label_11.setGeometry(QtCore.QRect(210, 60, 55, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.groupBox_8)
        self.label_12.setGeometry(QtCore.QRect(120, 130, 71, 16))
        self.label_12.setObjectName("label_12")
        self.label_10 = QtWidgets.QLabel(self.groupBox_7)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 151, 39))
        self.label_10.setObjectName("label_10")
        self.lines_check_box = QtWidgets.QCheckBox(self.groupBox_7)
        self.lines_check_box.setGeometry(QtCore.QRect(130, 70, 81, 20))
        self.lines_check_box.setChecked(True)
        self.lines_check_box.setObjectName("lines_check_box")
        self.circles_check_box = QtWidgets.QCheckBox(self.groupBox_7)
        self.circles_check_box.setGeometry(QtCore.QRect(230, 70, 81, 20))
        self.circles_check_box.setObjectName("circles_check_box")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox_7)
        self.groupBox_4.setGeometry(QtCore.QRect(669, 9, 271, 181))
        self.groupBox_4.setObjectName("groupBox_4")
        self.hough_rmin = QtWidgets.QLineEdit(self.groupBox_4)
        self.hough_rmin.setGeometry(QtCore.QRect(70, 30, 113, 22))
        self.hough_rmin.setObjectName("hough_rmin")
        self.hough_thresh = QtWidgets.QLineEdit(self.groupBox_4)
        self.hough_thresh.setGeometry(QtCore.QRect(10, 100, 113, 22))
        self.hough_thresh.setObjectName("hough_thresh")
        self.hough_step = QtWidgets.QLineEdit(self.groupBox_4)
        self.hough_step.setGeometry(QtCore.QRect(150, 100, 113, 22))
        self.hough_step.setObjectName("hough_step")
        self.label_13 = QtWidgets.QLabel(self.groupBox_4)
        self.label_13.setGeometry(QtCore.QRect(100, 60, 55, 16))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.groupBox_4)
        self.label_14.setGeometry(QtCore.QRect(10, 130, 111, 16))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setGeometry(QtCore.QRect(160, 130, 101, 16))
        self.label_15.setObjectName("label_15")
        self.gridLayout_11.addWidget(self.groupBox_7, 4, 0, 1, 3)
        self.page.addTab(self.tab, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.groupBox_9 = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox_9.setObjectName("groupBox_9")
        self.harris_mode_select = QtWidgets.QComboBox(self.groupBox_9)
        self.harris_mode_select.setGeometry(QtCore.QRect(30, 80, 161, 22))
        self.harris_mode_select.setObjectName("harris_mode_select")
        self.harris_mode_select.addItem("")
        self.harris_mode_select.addItem("")
        self.harris_mode_select.addItem("")
        self.harris_mode_select.addItem("")
        self.harris_k_input = QtWidgets.QLineEdit(self.groupBox_9)
        self.harris_k_input.setGeometry(QtCore.QRect(250, 80, 81, 22))
        self.harris_k_input.setObjectName("harris_k_input")
        self.label = QtWidgets.QLabel(self.groupBox_9)
        self.label.setGeometry(QtCore.QRect(210, 80, 31, 16))
        self.label.setObjectName("label")
        self.harris_window_size_input = QtWidgets.QLineEdit(self.groupBox_9)
        self.harris_window_size_input.setGeometry(QtCore.QRect(480, 80, 113, 22))
        self.harris_window_size_input.setObjectName("harris_window_size_input")
        self.label_2 = QtWidgets.QLabel(self.groupBox_9)
        self.label_2.setGeometry(QtCore.QRect(380, 80, 81, 16))
        self.label_2.setObjectName("label_2")
        self.harris_param_input = QtWidgets.QLineEdit(self.groupBox_9)
        self.harris_param_input.setGeometry(QtCore.QRect(80, 120, 81, 22))
        self.harris_param_input.setObjectName("harris_param_input")
        self.label_5 = QtWidgets.QLabel(self.groupBox_9)
        self.label_5.setGeometry(QtCore.QRect(30, 120, 55, 16))
        self.label_5.setObjectName("label_5")
        self.gridLayout_5.addWidget(self.groupBox_9, 4, 0, 1, 3)
        self.harris_image_name = QtWidgets.QLabel(self.tab_4)
        self.harris_image_name.setObjectName("harris_image_name")
        self.gridLayout_5.addWidget(self.harris_image_name, 1, 0, 1, 1)
        self.harris_input_image = QtWidgets.QLabel(self.tab_4)
        self.harris_input_image.setMinimumSize(QtCore.QSize(322, 322))
        self.harris_input_image.setMaximumSize(QtCore.QSize(322, 322))
        self.harris_input_image.setFrameShape(QtWidgets.QFrame.Box)
        self.harris_input_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.harris_input_image.setObjectName("harris_input_image")
        self.gridLayout_5.addWidget(self.harris_input_image, 1, 1, 2, 1)
        self.harris_image_output = QtWidgets.QLabel(self.tab_4)
        self.harris_image_output.setMinimumSize(QtCore.QSize(322, 322))
        self.harris_image_output.setMaximumSize(QtCore.QSize(322, 322))
        self.harris_image_output.setFrameShape(QtWidgets.QFrame.Box)
        self.harris_image_output.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.harris_image_output.setObjectName("harris_image_output")
        self.gridLayout_5.addWidget(self.harris_image_output, 1, 2, 2, 1)
        self.harris_load = QtWidgets.QPushButton(self.tab_4)
        self.harris_load.setObjectName("harris_load")
        self.gridLayout_5.addWidget(self.harris_load, 0, 0, 1, 1)
        self.harris_image_size = QtWidgets.QLabel(self.tab_4)
        self.harris_image_size.setObjectName("harris_image_size")
        self.gridLayout_5.addWidget(self.harris_image_size, 2, 0, 1, 1)
        self.harris_apply = QtWidgets.QPushButton(self.tab_4)
        self.harris_apply.setObjectName("harris_apply")
        self.gridLayout_5.addWidget(self.harris_apply, 3, 0, 1, 1)
        self.page.addTab(self.tab_4, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.snake_reset = QtWidgets.QPushButton(self.tab_2)
        self.snake_reset.setObjectName("snake_reset")
        self.gridLayout_6.addWidget(self.snake_reset, 6, 0, 1, 1)
        self.snake_load_image = QtWidgets.QPushButton(self.tab_2)
        self.snake_load_image.setObjectName("snake_load_image")
        self.gridLayout_6.addWidget(self.snake_load_image, 0, 0, 1, 1)
        self.snake_image_size = QtWidgets.QLabel(self.tab_2)
        self.snake_image_size.setObjectName("snake_image_size")
        self.gridLayout_6.addWidget(self.snake_image_size, 2, 0, 1, 1)
        self.snake_apply = QtWidgets.QPushButton(self.tab_2)
        self.snake_apply.setObjectName("snake_apply")
        self.gridLayout_6.addWidget(self.snake_apply, 5, 0, 1, 1)
        self.snake_input_image = QtWidgets.QLabel(self.tab_2)
        self.snake_input_image.setMinimumSize(QtCore.QSize(500, 500))
        self.snake_input_image.setMaximumSize(QtCore.QSize(322, 322))
        self.snake_input_image.setFrameShape(QtWidgets.QFrame.Box)
        self.snake_input_image.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.snake_input_image.setObjectName("snake_input_image")
        self.gridLayout_6.addWidget(self.snake_input_image, 0, 1, 3, 1)
        self.snake_image_name = QtWidgets.QLabel(self.tab_2)
        self.snake_image_name.setObjectName("snake_image_name")
        self.gridLayout_6.addWidget(self.snake_image_name, 1, 0, 1, 1)
        self.snake_perimeter = QtWidgets.QLabel(self.tab_2)
        self.snake_perimeter.setObjectName("snake_perimeter")
        self.gridLayout_6.addWidget(self.snake_perimeter, 10, 1, 1, 1)
        self.snake_clear_anchors = QtWidgets.QPushButton(self.tab_2)
        self.snake_clear_anchors.setObjectName("snake_clear_anchors")
        self.gridLayout_6.addWidget(self.snake_clear_anchors, 4, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setMinimumSize(QtCore.QSize(0, 200))
        self.groupBox_3.setObjectName("groupBox_3")
        self.snake_alpha_input = QtWidgets.QLineEdit(self.groupBox_3)
        self.snake_alpha_input.setGeometry(QtCore.QRect(120, 50, 113, 22))
        self.snake_alpha_input.setObjectName("snake_alpha_input")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(30, 50, 55, 16))
        self.label_6.setObjectName("label_6")
        self.snake_beta_input = QtWidgets.QLineEdit(self.groupBox_3)
        self.snake_beta_input.setGeometry(QtCore.QRect(120, 100, 113, 22))
        self.snake_beta_input.setObjectName("snake_beta_input")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(30, 100, 55, 16))
        self.label_7.setObjectName("label_7")
        self.snake_gamma_input = QtWidgets.QLineEdit(self.groupBox_3)
        self.snake_gamma_input.setGeometry(QtCore.QRect(120, 150, 113, 22))
        self.snake_gamma_input.setObjectName("snake_gamma_input")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(30, 150, 55, 16))
        self.label_8.setObjectName("label_8")
        self.snake_num_iter = QtWidgets.QLineEdit(self.groupBox_3)
        self.snake_num_iter.setGeometry(QtCore.QRect(290, 90, 113, 22))
        self.snake_num_iter.setObjectName("snake_num_iter")
        self.label_16 = QtWidgets.QLabel(self.groupBox_3)
        self.label_16.setGeometry(QtCore.QRect(290, 120, 121, 16))
        self.label_16.setObjectName("label_16")
        self.gridLayout_6.addWidget(self.groupBox_3, 8, 0, 1, 1)
        self.snake_xy = QtWidgets.QLabel(self.tab_2)
        self.snake_xy.setObjectName("snake_xy")
        self.gridLayout_6.addWidget(self.snake_xy, 9, 1, 1, 1)
        self.page.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.Template_input_image_B = QtWidgets.QLabel(self.tab_3)
        self.Template_input_image_B.setMinimumSize(QtCore.QSize(300, 300))
        self.Template_input_image_B.setMaximumSize(QtCore.QSize(450, 450))
        self.Template_input_image_B.setFrameShape(QtWidgets.QFrame.Box)
        self.Template_input_image_B.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Template_input_image_B.setObjectName("Template_input_image_B")
        self.gridLayout_7.addWidget(self.Template_input_image_B, 6, 1, 1, 1)
        self.Template_load_image_A = QtWidgets.QPushButton(self.tab_3)
        self.Template_load_image_A.setObjectName("Template_load_image_A")
        self.gridLayout_7.addWidget(self.Template_load_image_A, 0, 0, 1, 1)
        self.template_image_name_A = QtWidgets.QLabel(self.tab_3)
        self.template_image_name_A.setObjectName("template_image_name_A")
        self.gridLayout_7.addWidget(self.template_image_name_A, 3, 0, 1, 1)
        self.Template_match_button = QtWidgets.QPushButton(self.tab_3)
        self.Template_match_button.setObjectName("Template_match_button")
        self.gridLayout_7.addWidget(self.Template_match_button, 6, 6, 1, 1)
        self.template_image_size_A = QtWidgets.QLabel(self.tab_3)
        self.template_image_size_A.setObjectName("template_image_size_A")
        self.gridLayout_7.addWidget(self.template_image_size_A, 4, 0, 1, 4)
        self.Template_detected_patterns = QtWidgets.QLabel(self.tab_3)
        self.Template_detected_patterns.setMinimumSize(QtCore.QSize(300, 300))
        self.Template_detected_patterns.setMaximumSize(QtCore.QSize(450, 450))
        self.Template_detected_patterns.setFrameShape(QtWidgets.QFrame.Box)
        self.Template_detected_patterns.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Template_detected_patterns.setObjectName("Template_detected_patterns")
        self.gridLayout_7.addWidget(self.Template_detected_patterns, 6, 4, 1, 1)
        self.template_time_elapsed = QtWidgets.QLabel(self.tab_3)
        self.template_time_elapsed.setObjectName("template_time_elapsed")
        self.gridLayout_7.addWidget(self.template_time_elapsed, 7, 6, 1, 1)
        self.Template_input_image_A = QtWidgets.QLabel(self.tab_3)
        self.Template_input_image_A.setMinimumSize(QtCore.QSize(300, 300))
        self.Template_input_image_A.setMaximumSize(QtCore.QSize(450, 450))
        self.Template_input_image_A.setFrameShape(QtWidgets.QFrame.Box)
        self.Template_input_image_A.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Template_input_image_A.setObjectName("Template_input_image_A")
        self.gridLayout_7.addWidget(self.Template_input_image_A, 2, 1, 1, 1)
        self.template_image_name_B = QtWidgets.QLabel(self.tab_3)
        self.template_image_name_B.setObjectName("template_image_name_B")
        self.gridLayout_7.addWidget(self.template_image_name_B, 8, 0, 1, 4)
        self.Template_matching_space = QtWidgets.QLabel(self.tab_3)
        self.Template_matching_space.setMinimumSize(QtCore.QSize(300, 300))
        self.Template_matching_space.setMaximumSize(QtCore.QSize(450, 450))
        self.Template_matching_space.setFrameShape(QtWidgets.QFrame.Box)
        self.Template_matching_space.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.Template_matching_space.setObjectName("Template_matching_space")
        self.gridLayout_7.addWidget(self.Template_matching_space, 2, 4, 1, 1)
        self.Template_load_image_B = QtWidgets.QPushButton(self.tab_3)
        self.Template_load_image_B.setObjectName("Template_load_image_B")
        self.gridLayout_7.addWidget(self.Template_load_image_B, 5, 0, 1, 1)
        self.template_image_size_B = QtWidgets.QLabel(self.tab_3)
        self.template_image_size_B.setObjectName("template_image_size_B")
        self.gridLayout_7.addWidget(self.template_image_size_B, 10, 0, 1, 4)
        self.template_detection_parameters = QtWidgets.QGroupBox(self.tab_3)
        self.template_detection_parameters.setMinimumSize(QtCore.QSize(0, 200))
        self.template_detection_parameters.setMaximumSize(QtCore.QSize(500, 500))
        self.template_detection_parameters.setObjectName("template_detection_parameters")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.template_detection_parameters)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.template_mode_select = QtWidgets.QComboBox(self.template_detection_parameters)
        self.template_mode_select.setObjectName("template_mode_select")
        self.template_mode_select.addItem("")
        self.template_mode_select.addItem("")
        self.template_mode_select.addItem("")
        self.template_mode_select.addItem("")
        self.gridLayout_18.addWidget(self.template_mode_select, 0, 0, 1, 1)
        self.template_no_peaks = QtWidgets.QLabel(self.template_detection_parameters)
        self.template_no_peaks.setObjectName("template_no_peaks")
        self.gridLayout_18.addWidget(self.template_no_peaks, 2, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.template_detection_parameters)
        self.label_17.setObjectName("label_17")
        self.gridLayout_18.addWidget(self.label_17, 2, 3, 1, 1)
        self.no_peaks_input = QtWidgets.QLineEdit(self.template_detection_parameters)
        self.no_peaks_input.setObjectName("no_peaks_input")
        self.gridLayout_18.addWidget(self.no_peaks_input, 2, 1, 1, 1)
        self.gridLayout_7.addWidget(self.template_detection_parameters, 0, 6, 6, 1)
        self.page.addTab(self.tab_3, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.tab_5)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.sift_input_image_A = QtWidgets.QLabel(self.tab_5)
        self.sift_input_image_A.setMinimumSize(QtCore.QSize(300, 300))
        self.sift_input_image_A.setMaximumSize(QtCore.QSize(450, 450))
        self.sift_input_image_A.setFrameShape(QtWidgets.QFrame.Box)
        self.sift_input_image_A.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sift_input_image_A.setObjectName("sift_input_image_A")
        self.gridLayout_8.addWidget(self.sift_input_image_A, 1, 0, 1, 2)
        self.sift_input_image_B = QtWidgets.QLabel(self.tab_5)
        self.sift_input_image_B.setMinimumSize(QtCore.QSize(300, 300))
        self.sift_input_image_B.setMaximumSize(QtCore.QSize(450, 450))
        self.sift_input_image_B.setFrameShape(QtWidgets.QFrame.Box)
        self.sift_input_image_B.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sift_input_image_B.setObjectName("sift_input_image_B")
        self.gridLayout_8.addWidget(self.sift_input_image_B, 1, 2, 1, 2)
        self.sift_tunable_parameters = QtWidgets.QGroupBox(self.tab_5)
        self.sift_tunable_parameters.setMinimumSize(QtCore.QSize(0, 200))
        self.sift_tunable_parameters.setObjectName("sift_tunable_parameters")
        self.gridLayout_8.addWidget(self.sift_tunable_parameters, 1, 4, 2, 1)
        self.sift_image_name_A = QtWidgets.QLabel(self.tab_5)
        self.sift_image_name_A.setObjectName("sift_image_name_A")
        self.gridLayout_8.addWidget(self.sift_image_name_A, 2, 0, 1, 1)
        self.sift_image_name_B = QtWidgets.QLabel(self.tab_5)
        self.sift_image_name_B.setObjectName("sift_image_name_B")
        self.gridLayout_8.addWidget(self.sift_image_name_B, 2, 2, 1, 1)
        self.sift_image_size_A = QtWidgets.QLabel(self.tab_5)
        self.sift_image_size_A.setObjectName("sift_image_size_A")
        self.gridLayout_8.addWidget(self.sift_image_size_A, 3, 0, 1, 2)
        self.sift_image_size_B = QtWidgets.QLabel(self.tab_5)
        self.sift_image_size_B.setObjectName("sift_image_size_B")
        self.gridLayout_8.addWidget(self.sift_image_size_B, 3, 2, 1, 3)
        self.sift_features_matching = QtWidgets.QLabel(self.tab_5)
        self.sift_features_matching.setMinimumSize(QtCore.QSize(300, 300))
        self.sift_features_matching.setMaximumSize(QtCore.QSize(450, 450))
        self.sift_features_matching.setFrameShape(QtWidgets.QFrame.Box)
        self.sift_features_matching.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.sift_features_matching.setObjectName("sift_features_matching")
        self.gridLayout_8.addWidget(self.sift_features_matching, 4, 1, 3, 3)
        self.sift_match_button = QtWidgets.QPushButton(self.tab_5)
        self.sift_match_button.setObjectName("sift_match_button")
        self.gridLayout_8.addWidget(self.sift_match_button, 5, 4, 1, 1)
        self.sift_time_elapsed = QtWidgets.QLabel(self.tab_5)
        self.sift_time_elapsed.setObjectName("sift_time_elapsed")
        self.gridLayout_8.addWidget(self.sift_time_elapsed, 6, 4, 1, 1)
        self.sift_load_image_A = QtWidgets.QPushButton(self.tab_5)
        self.sift_load_image_A.setObjectName("sift_load_image_A")
        self.gridLayout_8.addWidget(self.sift_load_image_A, 0, 0, 1, 1)
        self.sift_load_image_B = QtWidgets.QPushButton(self.tab_5)
        self.sift_load_image_B.setObjectName("sift_load_image_B")
        self.gridLayout_8.addWidget(self.sift_load_image_B, 0, 2, 1, 1)
        self.page.addTab(self.tab_5, "")
        self.gridLayout.addWidget(self.page, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.page.setCurrentIndex(6)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.filter_input_image.setText(_translate("MainWindow", "Input image"))
        self.filter_image_name.setText(_translate("MainWindow", "Name:"))
        self.filter_browse_button.setText(_translate("MainWindow", "Load Image"))
        self.groupBox.setTitle(_translate("MainWindow", "Filter Settings"))
        self.label_3.setText(_translate("MainWindow", "Select Filter"))
        self.filter_combo_box.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.filter_combo_box.setItemText(2, _translate("MainWindow", "Canny"))
        self.filter_combo_box.setItemText(3, _translate("MainWindow", "Sobel"))
        self.filter_combo_box.setItemText(4, _translate("MainWindow", "Median"))
        self.filter_combo_box.setItemText(5, _translate("MainWindow", "Roberts"))
        self.filter_combo_box.setItemText(6, _translate("MainWindow", "Prewitt"))
        self.filter_combo_box.setItemText(7, _translate("MainWindow", "Average"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Additional Parameters"))
        self.label_4.setText(_translate("MainWindow", "Select Noise"))
        self.noise_combo_box.setItemText(1, _translate("MainWindow", "Gaussian"))
        self.noise_combo_box.setItemText(2, _translate("MainWindow", "Uniform"))
        self.noise_combo_box.setItemText(3, _translate("MainWindow", "Salt and Pepper"))
        self.filter_noise_image.setText(_translate("MainWindow", "Output image"))
        self.filter_image_size.setText(_translate("MainWindow", "Size:"))
        self.page.setTabText(self.page.indexOf(self.tab_filters), _translate("MainWindow", "Filters"))
        self.hist_output_image.setText(_translate("MainWindow", "Output image"))
        self.hist_browse_image.setText(_translate("MainWindow", "Load image"))
        self.hist_image_size.setText(_translate("MainWindow", "Size:"))
        self.hist_image_name.setText(_translate("MainWindow", "Name:"))
        self.selectrgb.setItemText(0, _translate("MainWindow", "Grey Image"))
        self.selectrgb.setItemText(1, _translate("MainWindow", "R color"))
        self.selectrgb.setItemText(2, _translate("MainWindow", "G color"))
        self.selectrgb.setItemText(3, _translate("MainWindow", "B color"))
        self.hist_input_image.setText(_translate("MainWindow", "Input image"))
        self.hist_combbox.setItemText(0, _translate("MainWindow", "Equalization"))
        self.hist_combbox.setItemText(1, _translate("MainWindow", "Normalization"))
        self.hist_combbox.setItemText(2, _translate("MainWindow", "Threshold"))
        self.page.setTabText(self.page.indexOf(self.tab_histograms), _translate("MainWindow", "Histograms"))
        self.hybrid_browse_image_1.setText(_translate("MainWindow", "Load image A"))
        self.hybrid_input_image_1.setText(_translate("MainWindow", "Input image A"))
        self.hybrid_output_image.setText(_translate("MainWindow", "Output image"))
        self.hybrid_image_1_name.setText(_translate("MainWindow", "Name:"))
        self.hybrid_image_1_size.setText(_translate("MainWindow", "Size:"))
        self.hybrid_browse_image_2.setText(_translate("MainWindow", "Load image B"))
        self.hybrid_input_image_2.setText(_translate("MainWindow", "Input image B"))
        self.hybrid_image_2_name.setText(_translate("MainWindow", "Name:"))
        self.hybrid_image_2_size.setText(_translate("MainWindow", "Size:"))
        self.hybrid_make_hybrid.setText(_translate("MainWindow", "Make Hybrid"))
        self.page.setTabText(self.page.indexOf(self.tab_hybrid), _translate("MainWindow", "Hybrid"))
        self.hough_load.setText(_translate("MainWindow", "Load image"))
        self.hough_input_image.setText(_translate("MainWindow", "Input image"))
        self.hough_output_image.setText(_translate("MainWindow", "Output image"))
        self.hough_image_name.setText(_translate("MainWindow", "Name:"))
        self.hough_image_size.setText(_translate("MainWindow", "Size:"))
        self.hough_apply.setText(_translate("MainWindow", "Apply"))
        self.groupBox_7.setTitle(_translate("MainWindow", "Operator Settings"))
        self.groupBox_8.setTitle(_translate("MainWindow", "Line"))
        self.hough_theta.setText(_translate("MainWindow", "1"))
        self.hough_rho.setText(_translate("MainWindow", "1"))
        self.hough_numpeaks.setText(_translate("MainWindow", "50"))
        self.label_9.setText(_translate("MainWindow", "Theta"))
        self.label_11.setText(_translate("MainWindow", "RHO"))
        self.label_12.setText(_translate("MainWindow", "Num. Peaks"))
        self.label_10.setText(_translate("MainWindow", "Select Shapes"))
        self.lines_check_box.setText(_translate("MainWindow", "Lines"))
        self.circles_check_box.setText(_translate("MainWindow", "Circles"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Circle"))
        self.hough_rmin.setText(_translate("MainWindow", "18"))
        self.hough_thresh.setText(_translate("MainWindow", "0.3"))
        self.hough_step.setText(_translate("MainWindow", "100"))
        self.label_13.setText(_translate("MainWindow", "R min"))
        self.label_14.setText(_translate("MainWindow", "Threshold 0.1 : 1"))
        self.label_15.setText(_translate("MainWindow", "Step 5 : 360"))
        self.page.setTabText(self.page.indexOf(self.tab), _translate("MainWindow", "Hough"))
        self.groupBox_9.setTitle(_translate("MainWindow", "Operator Settings"))
        self.harris_mode_select.setItemText(0, _translate("MainWindow", "Thresholding"))
        self.harris_mode_select.setItemText(1, _translate("MainWindow", "Local Thresholding"))
        self.harris_mode_select.setItemText(2, _translate("MainWindow", "Non Maxima Supression"))
        self.harris_mode_select.setItemText(3, _translate("MainWindow", "Local Maxima Extraction"))
        self.harris_k_input.setText(_translate("MainWindow", "0.04"))
        self.label.setText(_translate("MainWindow", "K"))
        self.harris_window_size_input.setText(_translate("MainWindow", "5"))
        self.label_2.setText(_translate("MainWindow", "Window Size"))
        self.harris_param_input.setText(_translate("MainWindow", "1000"))
        self.label_5.setText(_translate("MainWindow", "Param"))
        self.harris_image_name.setText(_translate("MainWindow", "Name:"))
        self.harris_input_image.setText(_translate("MainWindow", "Input image"))
        self.harris_image_output.setText(_translate("MainWindow", "Output image"))
        self.harris_load.setText(_translate("MainWindow", "Load image"))
        self.harris_image_size.setText(_translate("MainWindow", "Size:"))
        self.harris_apply.setText(_translate("MainWindow", "Apply"))
        self.page.setTabText(self.page.indexOf(self.tab_4), _translate("MainWindow", "Harris"))
        self.snake_reset.setText(_translate("MainWindow", "Reset"))
        self.snake_load_image.setText(_translate("MainWindow", "Load image"))
        self.snake_image_size.setText(_translate("MainWindow", "Size:"))
        self.snake_apply.setText(_translate("MainWindow", "Apply"))
        self.snake_input_image.setText(_translate("MainWindow", "Input image"))
        self.snake_image_name.setText(_translate("MainWindow", "Name:"))
        self.snake_perimeter.setText(_translate("MainWindow", "TextLabel"))
        self.snake_clear_anchors.setText(_translate("MainWindow", "Clear Anchors"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Countour Settings"))
        self.snake_alpha_input.setText(_translate("MainWindow", "300"))
        self.label_6.setText(_translate("MainWindow", "Alpha"))
        self.snake_beta_input.setText(_translate("MainWindow", "2"))
        self.label_7.setText(_translate("MainWindow", "Beta"))
        self.snake_gamma_input.setText(_translate("MainWindow", "50"))
        self.label_8.setText(_translate("MainWindow", "Gamma"))
        self.snake_num_iter.setText(_translate("MainWindow", "100"))
        self.label_16.setText(_translate("MainWindow", "Number of Iteration"))
        self.snake_xy.setText(_translate("MainWindow", "TextLabel"))
        self.page.setTabText(self.page.indexOf(self.tab_2), _translate("MainWindow", "Active Contour"))
        self.Template_input_image_B.setText(_translate("MainWindow", "Input image B"))
        self.Template_load_image_A.setText(_translate("MainWindow", " Load image A"))
        self.template_image_name_A.setText(_translate("MainWindow", "Name:"))
        self.Template_match_button.setText(_translate("MainWindow", "Match"))
        self.template_image_size_A.setText(_translate("MainWindow", "Size:"))
        self.Template_detected_patterns.setText(_translate("MainWindow", "Detected patterns"))
        self.template_time_elapsed.setText(_translate("MainWindow", "Time elapsed:"))
        self.Template_input_image_A.setText(_translate("MainWindow", "Input image A"))
        self.template_image_name_B.setText(_translate("MainWindow", "Name:"))
        self.Template_matching_space.setText(_translate("MainWindow", "Matching Space"))
        self.Template_load_image_B.setText(_translate("MainWindow", "Load image B"))
        self.template_image_size_B.setText(_translate("MainWindow", "Size:"))
        self.template_detection_parameters.setTitle(_translate("MainWindow", "Detection Parameters"))
        self.template_mode_select.setItemText(0, _translate("MainWindow", "Correlation"))
        self.template_mode_select.setItemText(1, _translate("MainWindow", "Zero-mean"))
        self.template_mode_select.setItemText(2, _translate("MainWindow", "SSD"))
        self.template_mode_select.setItemText(3, _translate("MainWindow", "Normalized cross correlation"))
        self.template_no_peaks.setText(_translate("MainWindow", "         No. of peaks:"))
        self.label_17.setText(_translate("MainWindow", "1   :    30"))
        self.no_peaks_input.setText(_translate("MainWindow", "4"))
        self.page.setTabText(self.page.indexOf(self.tab_3), _translate("MainWindow", "Template Matching"))
        self.sift_input_image_A.setText(_translate("MainWindow", "Input image A"))
        self.sift_input_image_B.setText(_translate("MainWindow", "Input image B"))
        self.sift_tunable_parameters.setTitle(_translate("MainWindow", "Tunable parameters"))
        self.sift_image_name_A.setText(_translate("MainWindow", "Name:"))
        self.sift_image_name_B.setText(_translate("MainWindow", "Name:"))
        self.sift_image_size_A.setText(_translate("MainWindow", "Size:"))
        self.sift_image_size_B.setText(_translate("MainWindow", "Size:"))
        self.sift_features_matching.setText(_translate("MainWindow", "Features Matching"))
        self.sift_match_button.setText(_translate("MainWindow", "Match"))
        self.sift_time_elapsed.setText(_translate("MainWindow", "Time elapsed:"))
        self.sift_load_image_A.setText(_translate("MainWindow", " Load image A"))
        self.sift_load_image_B.setText(_translate("MainWindow", " Load image B"))
        self.page.setTabText(self.page.indexOf(self.tab_5), _translate("MainWindow", "Sift"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
